### ISSUE TITLE
It Needs .NET

### ISSUE THREAD

**Issue by michaelleepow90** [Antoher0101/CardFilePBX#2]
It keeps saying that I don't have .NET installed... When I press yes, nothing happens & the app exits. "See Pic"
![Missing NET](https://github.com/Antoher0101/CardFilePBX/assets/25166581/f7fec3e7-0c97-4284-b728-c91712163374)

**Comment by Antoher0101** [comment]
maybe you should try the 1.0.0 release, which contains .net... But why?

> It keeps saying that I don't have .NET installed... When I press yes, nothing happens & the app exits. "See Pic" ![Missing NET](https://private-user-images.githubusercontent.com/25166581/312670706-f7fec3e7-0c97-4284-b728-c91712163374.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzODMxMTksIm5iZiI6MTcxMDM4MjgxOSwicGF0aCI6Ii8yNTE2NjU4MS8zMTI2NzA3MDYtZjdmZWMzZTctMGM5Ny00Mjg0LWI3MjgtYzkxNzEyMTYzMzc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDAyMjAxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1NDBlNDRkZGZiYThjNjkwMjVjOWU5NmU1OTNhMWJmZGIyZjJlNDg1NTU0OWU3YzZkYWVhMWQ1OWFhZjJhMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JpxRRH3_SEEM_onpDuR-CjfZf3Gou0hnuG-VmGbs9Jc)

**Comment by michaelleepow90** [comment]
Not sure... I have all the .NET's installed... Are they planning on fixing this bug in the latest version?

**Comment by michaelleepow90** [comment]
Is there an English version? I don't understand this language... This is version 1.0.0.
![Missing NET 1](https://github.com/Antoher0101/CardFilePBX/assets/25166581/844d55d6-ffcd-47b7-a3bd-b502db57ef85)

**Comment by Antoher0101** [comment]
This is just a course project for the university. does it really need to be updated?

**Comment by michaelleepow90** [comment]
No, Just checking, thanks, hoping that there would be English version..

**Comment by michaelleepow90** [comment]
- Oh, just to be aware, I heard on YouTube that Microsoft will start blocking all customizing apps in 24H2 of Windows 11 Build 26100. I caught the news from the "Windows, Computers & Technology" channel.
